version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
  snyk: snyk/snyk@0.0.8
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run:
                name: 'Lint'
                command: yarn run lint
            - run:
                name: 'Build'
                command: yarn run build
            - snyk/scan:
                protect: true
workflows:
  build_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: master
